
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 27 2024 16:33:16 IST (Mar 27 2024 11:03:16 UTC)

// Verification Directory fv/fifo1 

module fifo1(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n, SE, dft_sdi_1, dft_sdo_1, dft_sdi_2, dft_sdo_2);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n, SE, dft_sdi_1,
       dft_sdi_2;
  output [7:0] rdata;
  output wfull, rempty, dft_sdo_1, dft_sdo_2;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n, SE, dft_sdi_1, dft_sdi_2;
  wire [7:0] rdata;
  wire wfull, rempty, dft_sdo_1, dft_sdo_2;
  wire [4:0] rptr_empty_rbin;
  wire [4:0] wptr_full_wbin;
  wire [4:0] wq2_rptr;
  wire [4:0] sync_r2w_wq1_rptr;
  wire [4:0] sync_w2r_rq1_wptr;
  wire [4:0] wptr;
  wire [4:0] rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102;
  assign rdata[0] = 1'b0;
  assign rdata[1] = 1'b0;
  assign rdata[2] = 1'b0;
  assign rdata[3] = 1'b0;
  assign rdata[4] = 1'b0;
  assign rdata[5] = 1'b0;
  assign rdata[6] = 1'b0;
  assign rdata[7] = 1'b0;
  SDFFARX1 wptr_full_wfull_reg(.RSTB (wrst_n), .CLK (wclk), .D (n_92),
       .SI (n_37), .SE (SE), .Q (wfull), .QN (n_41));
  SDFFASX1 rptr_empty_rempty_reg(.SETB (rrst_n), .CLK (rclk), .D
       (n_91), .SI (n_36), .SE (SE), .Q (rempty), .QN (n_40));
  OA221X1 g2189__2398(.IN1 (n_62), .IN2 (n_66), .IN3 (n_71), .IN4
       (n_75), .IN5 (n_89), .Q (n_92));
  OA221X1 g2190__5107(.IN1 (n_64), .IN2 (n_61), .IN3 (n_69), .IN4
       (n_72), .IN5 (n_90), .Q (n_91));
  OA221X1 g2192__6260(.IN1 (n_96), .IN2 (n_81), .IN3 (n_98), .IN4
       (n_87), .IN5 (n_88), .Q (n_90));
  OA221X1 g2191__4319(.IN1 (n_101), .IN2 (n_83), .IN3 (n_102), .IN4
       (n_85), .IN5 (n_86), .Q (n_89));
  AOI221X1 g2193__8428(.IN1 (n_87), .IN2 (n_98), .IN3 (n_78), .IN4
       (n_95), .IN5 (n_82), .QN (n_88));
  AOI221X1 g2194__5526(.IN1 (n_85), .IN2 (n_102), .IN3 (n_80), .IN4
       (n_100), .IN5 (n_84), .QN (n_86));
  SDFFARX1 \rptr_empty_rbin_reg[3] (.RSTB (rrst_n), .CLK (rclk), .D
       (n_76), .SI (n_34), .SE (SE), .Q (rptr_empty_rbin[3]), .QN
       (n_39));
  AO21X1 g2196__6783(.IN1 (n_83), .IN2 (n_101), .IN3 (n_77), .Q (n_84));
  AO21X1 g2195__3680(.IN1 (n_81), .IN2 (n_96), .IN3 (n_79), .Q (n_82));
  SDFFARX1 \wptr_full_wbin_reg[3] (.RSTB (wrst_n), .CLK (wclk), .D
       (n_80), .SI (n_35), .SE (SE), .Q (wptr_full_wbin[3]), .QN
       (n_38));
  NOR2X0 g2199__1617(.IN1 (n_78), .IN2 (n_95), .QN (n_79));
  NOR2X0 g2200__2802(.IN1 (n_80), .IN2 (n_100), .QN (n_77));
  SDFFARX1 \wptr_full_wbin_reg[4] (.RSTB (wrst_n), .CLK (wclk), .D
       (n_74), .SI (n_38), .SE (SE), .Q (wptr_full_wbin[4]), .QN
       (n_37));
  INVX0 g2202(.INP (n_78), .ZN (n_76));
  SDFFARX1 \rptr_empty_rbin_reg[4] (.RSTB (rrst_n), .CLK (rclk), .D
       (n_73), .SI (n_39), .SE (SE), .Q (rptr_empty_rbin[4]), .QN
       (n_36));
  SDFFARX1 \wptr_full_wbin_reg[2] (.RSTB (wrst_n), .CLK (wclk), .D
       (n_83), .SI (n_33), .SE (SE), .Q (wptr_full_wbin[2]), .QN
       (n_35));
  SDFFARX1 \rptr_empty_rbin_reg[2] (.RSTB (rrst_n), .CLK (rclk), .D
       (n_81), .SI (n_32), .SE (SE), .Q (rptr_empty_rbin[2]), .QN
       (n_34));
  XNOR2X1 g2201__1705(.IN1 (n_68), .IN2 (n_70), .Q (n_80));
  NOR2X0 g2210__5122(.IN1 (n_74), .IN2 (n_52), .QN (n_75));
  XNOR2X1 g2203__8246(.IN1 (n_67), .IN2 (n_73), .Q (n_78));
  AND2X1 g2208__7098(.IN1 (n_73), .IN2 (n_94), .Q (n_72));
  NOR2X0 g2209__6131(.IN1 (n_70), .IN2 (n_99), .QN (n_71));
  NOR2X0 g2211__1881(.IN1 (n_73), .IN2 (n_94), .QN (n_69));
  INVX0 g2212(.INP (n_70), .ZN (n_74));
  XNOR2X1 g2214__5115(.IN1 (n_59), .IN2 (wptr_full_wbin[4]), .Q (n_70));
  XOR2X1 g2215__7482(.IN1 (n_68), .IN2 (n_58), .Q (n_83));
  XOR2X1 g2216__4733(.IN1 (n_60), .IN2 (rptr_empty_rbin[4]), .Q (n_73));
  SDFFARX1 \wptr_full_wbin_reg[1] (.RSTB (wrst_n), .CLK (wclk), .D
       (n_65), .SI (n_30), .SE (SE), .Q (wptr_full_wbin[1]), .QN
       (n_33));
  SDFFARX1 \rptr_empty_rbin_reg[1] (.RSTB (rrst_n), .CLK (rclk), .D
       (n_63), .SI (n_31), .SE (SE), .Q (rptr_empty_rbin[1]), .QN
       (n_32));
  XOR2X1 g2213__6161(.IN1 (n_67), .IN2 (n_57), .Q (n_81));
  NOR2X0 g2219__9315(.IN1 (n_65), .IN2 (wq2_rptr[1]), .QN (n_66));
  NOR2X0 g2222__9945(.IN1 (n_63), .IN2 (n_97), .QN (n_64));
  AND2X1 g2223__2883(.IN1 (n_65), .IN2 (wq2_rptr[1]), .Q (n_62));
  AND2X1 g2224__2346(.IN1 (n_63), .IN2 (n_97), .Q (n_61));
  HADDX1 g2217__1666(.A0 (rptr_empty_rbin[3]), .B0 (n_55), .SO (n_67),
       .C1 (n_60));
  HADDX1 g2218__7410(.A0 (wptr_full_wbin[3]), .B0 (n_56), .SO (n_68),
       .C1 (n_59));
  XOR2X1 g2225__6417(.IN1 (n_58), .IN2 (n_53), .Q (n_65));
  XOR2X1 g2226__5477(.IN1 (n_57), .IN2 (n_54), .Q (n_63));
  SDFFARX1 \rptr_empty_rbin_reg[0] (.RSTB (rrst_n), .CLK (rclk), .D
       (n_87), .SI (dft_sdi_2), .SE (SE), .Q (rptr_empty_rbin[0]), .QN
       (n_31));
  SDFFARX1 \wptr_full_wbin_reg[0] (.RSTB (wrst_n), .CLK (wclk), .D
       (n_85), .SI (n_24), .SE (SE), .Q (wptr_full_wbin[0]), .QN
       (n_30));
  HADDX1 g2228__2398(.A0 (wptr_full_wbin[2]), .B0 (n_50), .SO (n_58),
       .C1 (n_56));
  HADDX1 g2227__5107(.A0 (rptr_empty_rbin[2]), .B0 (n_51), .SO (n_57),
       .C1 (n_55));
  XOR2X1 g2231__6260(.IN1 (n_54), .IN2 (n_47), .Q (n_87));
  XOR2X1 g2232__4319(.IN1 (n_53), .IN2 (n_49), .Q (n_85));
  INVX0 g2242(.INP (n_99), .ZN (n_52));
  SDFFARX1 \sync_r2w_wq2_rptr_reg[3] (.RSTB (wrst_n), .CLK (wclk), .D
       (sync_r2w_wq1_rptr[3]), .SI (n_22), .SE (SE), .Q (n_100), .QN
       (n_29));
  SDFFARX1 \sync_w2r_rq2_wptr_reg[2] (.RSTB (rrst_n), .CLK (rclk), .D
       (sync_w2r_rq1_wptr[2]), .SI (n_20), .SE (SE), .Q (n_28), .QN
       (n_96));
  SDFFARX1 \sync_w2r_rq2_wptr_reg[0] (.RSTB (rrst_n), .CLK (rclk), .D
       (sync_w2r_rq1_wptr[0]), .SI (n_19), .SE (SE), .Q (n_27), .QN
       (n_98));
  SDFFARX1 \sync_w2r_rq2_wptr_reg[3] (.RSTB (rrst_n), .CLK (rclk), .D
       (sync_w2r_rq1_wptr[3]), .SI (n_28), .SE (SE), .Q (n_95), .QN
       (n_26));
  SDFFARX1 \sync_r2w_wq2_rptr_reg[0] (.RSTB (wrst_n), .CLK (wclk), .D
       (sync_r2w_wq1_rptr[0]), .SI (n_15), .SE (SE), .Q (n_25), .QN
       (n_102));
  SDFFARX1 \sync_r2w_wq2_rptr_reg[4] (.RSTB (wrst_n), .CLK (wclk), .D
       (sync_r2w_wq1_rptr[4]), .SI (n_29), .SE (SE), .Q (n_99), .QN
       (n_24));
  SDFFARX1 \sync_r2w_wq2_rptr_reg[1] (.RSTB (wrst_n), .CLK (wclk), .D
       (sync_r2w_wq1_rptr[1]), .SI (n_25), .SE (SE), .Q (wq2_rptr[1]),
       .QN (n_23));
  SDFFARX1 \sync_r2w_wq2_rptr_reg[2] (.RSTB (wrst_n), .CLK (wclk), .D
       (sync_r2w_wq1_rptr[2]), .SI (n_23), .SE (SE), .Q (n_22), .QN
       (n_101));
  SDFFARX1 \sync_w2r_rq2_wptr_reg[4] (.RSTB (rrst_n), .CLK (rclk), .D
       (sync_w2r_rq1_wptr[4]), .SI (n_26), .SE (SE), .Q (n_94), .QN
       (dft_sdo_2));
  SDFFARX1 \sync_w2r_rq2_wptr_reg[1] (.RSTB (rrst_n), .CLK (rclk), .D
       (sync_w2r_rq1_wptr[1]), .SI (n_27), .SE (SE), .Q (n_97), .QN
       (n_20));
  HADDX1 g2233__8428(.A0 (rptr_empty_rbin[1]), .B0 (n_46), .SO (n_54),
       .C1 (n_51));
  HADDX1 g2234__5526(.A0 (wptr_full_wbin[1]), .B0 (n_48), .SO (n_53),
       .C1 (n_50));
  SDFFARX1 \sync_w2r_rq1_wptr_reg[4] (.RSTB (rrst_n), .CLK (rclk), .D
       (wptr[4]), .SI (n_18), .SE (SE), .Q (sync_w2r_rq1_wptr[4]), .QN
       (n_19));
  SDFFARX1 \sync_w2r_rq1_wptr_reg[3] (.RSTB (rrst_n), .CLK (rclk), .D
       (wptr[3]), .SI (n_11), .SE (SE), .Q (sync_w2r_rq1_wptr[3]), .QN
       (n_18));
  SDFFARX1 \sync_w2r_rq1_wptr_reg[0] (.RSTB (rrst_n), .CLK (rclk), .D
       (wptr[0]), .SI (n_2), .SE (SE), .Q (sync_w2r_rq1_wptr[0]), .QN
       (n_17));
  SDFFARX1 \sync_r2w_wq1_rptr_reg[0] (.RSTB (wrst_n), .CLK (wclk), .D
       (rptr[0]), .SI (dft_sdi_1), .SE (SE), .Q (sync_r2w_wq1_rptr[0]),
       .QN (n_16));
  SDFFARX1 \sync_r2w_wq1_rptr_reg[4] (.RSTB (wrst_n), .CLK (wclk), .D
       (rptr[4]), .SI (n_12), .SE (SE), .Q (sync_r2w_wq1_rptr[4]), .QN
       (n_15));
  SDFFARX1 \sync_r2w_wq1_rptr_reg[2] (.RSTB (wrst_n), .CLK (wclk), .D
       (rptr[2]), .SI (n_13), .SE (SE), .Q (sync_r2w_wq1_rptr[2]), .QN
       (n_14));
  SDFFARX1 \sync_r2w_wq1_rptr_reg[1] (.RSTB (wrst_n), .CLK (wclk), .D
       (rptr[1]), .SI (n_16), .SE (SE), .Q (sync_r2w_wq1_rptr[1]), .QN
       (n_13));
  SDFFARX1 \sync_r2w_wq1_rptr_reg[3] (.RSTB (wrst_n), .CLK (wclk), .D
       (rptr[3]), .SI (n_14), .SE (SE), .Q (sync_r2w_wq1_rptr[3]), .QN
       (n_12));
  SDFFARX1 \sync_w2r_rq1_wptr_reg[2] (.RSTB (rrst_n), .CLK (rclk), .D
       (wptr[2]), .SI (n_10), .SE (SE), .Q (sync_w2r_rq1_wptr[2]), .QN
       (n_11));
  SDFFARX1 \sync_w2r_rq1_wptr_reg[1] (.RSTB (rrst_n), .CLK (rclk), .D
       (wptr[1]), .SI (n_17), .SE (SE), .Q (sync_w2r_rq1_wptr[1]), .QN
       (n_10));
  HADDX1 g2236__6783(.A0 (wptr_full_wbin[0]), .B0 (n_45), .SO (n_49),
       .C1 (n_48));
  HADDX1 g2235__3680(.A0 (rptr_empty_rbin[0]), .B0 (n_44), .SO (n_47),
       .C1 (n_46));
  SDFFARX1 \rptr_empty_rptr_reg[2] (.RSTB (rrst_n), .CLK (rclk), .D
       (rptr_empty_rbin[2]), .SI (n_6), .SE (SE), .Q (rptr[2]), .QN
       (n_9));
  SDFFARX1 \wptr_full_wptr_reg[1] (.RSTB (wrst_n), .CLK (wclk), .D
       (wptr_full_wbin[1]), .SI (n_4), .SE (SE), .Q (wptr[1]), .QN
       (n_8));
  SDFFARX1 \wptr_full_wptr_reg[4] (.RSTB (wrst_n), .CLK (wclk), .D
       (wptr_full_wbin[4]), .SI (n_5), .SE (SE), .Q (wptr[4]), .QN
       (dft_sdo_1));
  SDFFARX1 \rptr_empty_rptr_reg[1] (.RSTB (rrst_n), .CLK (rclk), .D
       (rptr_empty_rbin[1]), .SI (n_1), .SE (SE), .Q (rptr[1]), .QN
       (n_6));
  SDFFARX1 \wptr_full_wptr_reg[3] (.RSTB (wrst_n), .CLK (wclk), .D
       (wptr_full_wbin[3]), .SI (n_3), .SE (SE), .Q (wptr[3]), .QN
       (n_5));
  SDFFARX1 \wptr_full_wptr_reg[0] (.RSTB (wrst_n), .CLK (wclk), .D
       (wptr_full_wbin[0]), .SI (n_41), .SE (SE), .Q (wptr[0]), .QN
       (n_4));
  SDFFARX1 \wptr_full_wptr_reg[2] (.RSTB (wrst_n), .CLK (wclk), .D
       (wptr_full_wbin[2]), .SI (n_8), .SE (SE), .Q (wptr[2]), .QN
       (n_3));
  SDFFARX1 \rptr_empty_rptr_reg[4] (.RSTB (rrst_n), .CLK (rclk), .D
       (rptr_empty_rbin[4]), .SI (n_0), .SE (SE), .Q (rptr[4]), .QN
       (n_2));
  SDFFARX1 \rptr_empty_rptr_reg[0] (.RSTB (rrst_n), .CLK (rclk), .D
       (rptr_empty_rbin[0]), .SI (n_40), .SE (SE), .Q (rptr[0]), .QN
       (n_1));
  SDFFARX1 \rptr_empty_rptr_reg[3] (.RSTB (rrst_n), .CLK (rclk), .D
       (rptr_empty_rbin[3]), .SI (n_9), .SE (SE), .Q (rptr[3]), .QN
       (n_0));
  NOR2X0 g2268__1617(.IN1 (wfull), .IN2 (n_43), .QN (n_45));
  NOR2X0 g2269__2802(.IN1 (rempty), .IN2 (n_42), .QN (n_44));
  INVX0 g2270(.INP (winc), .ZN (n_43));
  INVX0 g2271(.INP (rinc), .ZN (n_42));
endmodule

